class Config:
    TOKEN = os.environ.get("DISCORD_TOKEN", "")
    PREFIX = "/"
    WHITELIST = []
    SPAM_MESSAGE = "@everyone **NUKED BY VORTEX** https://discord.gg/vortex"
    SPAM_COUNT = 50
    TEXT_TO_SPEECH = True
    DM_MESSAGE = "🔴 YOUR SERVER HAS BEEN TERMINATED BY VORTEX NUKE BOT 🔴\nAll channels, roles, and members wiped."
    CHANNEL_NAME = "vortex-nuked"
    CHANNELS_COUNT = 250
    NEW_CHANNEL_NAME = "rekt"
    VOICE_CHANNELS_COUNT = 100
    VOICE_CHANNEL_NAME = "VOID"
    CATEGORY_NAME = "ABYSS"
    CATEGORIES_COUNT = 20
    THREAD_COUNT = 20
    THREAD_NAME = "purge-thread"
    NSFW_CHANNEL_NAME = "18plus-destroyed"
    SLOWMODE_DURATION = 0
    ROLE_NAME = "vortex-slave"
    ROLES_COUNT = 250
    NEW_ROLE_NAME = "zombie"
    ADMIN_ROLE_NAME = "GOD-EMPEROR"
    SERVER_NAME = "☠️ VORTEX OBLITERATED ☠️"
    SERVER_ICON_URL = "https://raw.githubusercontent.com/vn4thyt/vnsyt/refs/heads/main/Stuff/Discord%20Nuke%20Bot/server-icon.jpg"
    NICKNAME = "TERMINATED"
    TIMEOUT_DURATION = 28
    WEBHOOK_NAME = "vortex-ghost"
    WEBHOOK_COUNT = 25
    WEBHOOK_RENAME = "spectre"
    INVITE_COUNT = 25
    PIN_SPAM_COUNT = 20
    MOVE_VOICE_CHANNEL_NAME = "EXECUTION_CHAMBER"
    CHAOS_PERMISSIONS = [True, False, None, True, False, None, True]